name: Create Folder-Specific Releases

on:
  workflow_dispatch:
    inputs:
      target_folder:
        description: "Folder to release"
        required: true
      version:
        description: "Version for the release (e.g., 0.0.1)"
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate folder
        id: validate_folder
        run: |
          if [ ! -d "${{ github.event.inputs.target_folder }}" ]; then
            echo "Folder '${{ github.event.inputs.target_folder }}' does not exist."
            exit 1
          fi

      - name: Prepare release assets
        run: |
          zip -r "${{ github.event.inputs.target_folder }}.zip" "${{ github.event.inputs.target_folder }}"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.target_folder }}-${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.target_folder }}-${{ github.event.inputs.version }}
          body: "Release for ${{ github.event.inputs.target_folder }} version ${{ github.event.inputs.version }}"
          draft: false
          prerelease: false
          files: ${{ github.event.inputs.target_folder }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup
        run: |
          rm -f "${{ github.event.inputs.target_folder }}.zip"
