name: Create Release Tag Based on Folder

on:
  push:
    paths:
      - "rust/**"
    branches:
      - main

permissions:
  contents: write

jobs:
  create-release-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Determine folder and new tag
        id: new_tag
        run: |
          folder=""
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "^rust/"; then
            folder="rust"
          fi

          if [ -z "$folder" ]; then
            echo "No valid folder detected."
            exit 1
          fi
          echo "Folder: $folder"

          latest_tag=$(git tag --list "${folder}*" | sort -V | tail -n 1 || echo "${folder}-0.0.0")
          echo "Latest tag: $latest_tag"

          major=$(echo $latest_tag | cut -d. -f1 | sed "s/${folder}//" || echo "0")
          minor=$(echo $latest_tag | cut -d. -f2 || echo "0")
          patch=$(echo $latest_tag | cut -d. -f3 || echo "0")

          major=${major:-0}
          minor=${minor:-0}
          patch=${patch:-0}

          new_tag="${folder}-${major}.${minor}.$((patch + 1))"
          echo "New tag: $new_tag"
          echo "folder=$folder" >> $GITHUB_OUTPUT
          echo "tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag ${{ steps.new_tag.outputs.tag }}
          git push origin ${{ steps.new_tag.outputs.tag }}

      - name: Package folder as asset
        run: |
          mkdir -p release-assets
          zip -r release-assets/${{ steps.new_tag.outputs.folder }}.zip ${{ steps.new_tag.outputs.folder }}
        shell: bash

      - name: Create GitHub Release with asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.new_tag.outputs.tag }}
          asset_path: release-assets/${{ steps.new_tag.outputs.folder }}.zip
          asset_name: ${{ steps.new_tag.outputs.folder }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
